linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - protogetter
    - scopelint
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-dirs:
    - internal/gen
    - cmd/dev
    - repos